/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ale.adq.gal.aut.cma.api;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;

import javax.sql.DataSource;

@SpringBootApplication
public class App {

    @Autowired
    DataSource datasourcre;

    public static void main(String[] args) throws Exception {
        SpringApplication.run(App.class, args);
    }
}
